### ISSUE TITLE
OIDC flow not redirecting to logon page

### ISSUE THREAD

**Issue by codebude** [waza-ari/fastapi-keycloak-middleware#10]
Hello waza-ari,

I have some problems implementing your library in my FastAPI project. Your readme says, that OIDC is supported. So I assumed that, when calling a protected endpoint without an Authorization header, the middleware would redirect me (in OIDC manner) to my Keycloaks login page.

Actually the redirect doesn't happen, but the API responds simply with: `Your request is missing an 'Authorization' HTTP header`
How to enable the OIDC flow?

**Comment by waza-ari** [comment]
Hi,

there is different flows that can be used, you can read on them on various pages, one example here: https://developer.okta.com/docs/concepts/oauth-openid/#openid-connect

In no case the backend would be responsible to redirect the user anywhere, it doesn't have the power to do so. You would generally have some front end (the same that is sending the requests to FastAPI in the first place), this would be responsible for redirecting the user to Keycloak.
