### ISSUE TITLE
update Keycloak configuration 

### ISSUE THREAD

**Issue by hokiegeek2** [waza-ari/fastapi-keycloak-middleware#11]
Great project! Would like to do the following:

1. Add verify field to KeycloakConfiguration as is possible in [KeycloakOpenID](https://github.com/marcospereirampj/python-keycloak/blob/5957607ad07536b94d878c3ce5d403c212b35220/src/keycloak/keycloak_openid.py#L69)
2. make keycloak_openid an instance attribute of KeycloakBackend

**Comment by hokiegeek2** [comment]
@waza-ari are you good w/ this PR or do you need more info?

**Comment by waza-ari** [comment]
Hi @hokiegeek2,

I've created a test release v0.3.0 on the Test PyPi instance: https://test.pypi.org/project/fastapi-keycloak-middleware/

Would you be willing to [use the test repository](https://stackoverflow.com/questions/73447611/how-do-i-install-packages-from-test-pypi-org-using-poetry) and use the v0.3.0 version?

**Comment by hokiegeek2** [comment]
@waza-ari absolutely, will do so next week.

**Comment by hokiegeek2** [comment]
@waza-ari argh, sorry for the delay on this! I uninstalled my fork and installed [0.3.0](https://test.pypi.org/project/fastapi-keycloak-middleware/) from test.pypi and everything looks great. I recommend moving this to the main pypi repo.
