### ISSUE TITLE
DeprecationWarning: pkg_resources is deprecated

### ISSUE THREAD

**Issue by codebude** [waza-ari/fastapi-keycloak-middleware#13]
The `import pkg_resources` in *_version.py* triggers a DeprecationWarning:

```shell
.venv\Lib\site-packages\keycloak\_version.py:24: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
```

There is a migration guide that shows how to migrate from the deprecated code:
https://importlib-metadata.readthedocs.io/en/latest/migration.html#pkg-resources-get-distribution

Can you consider this for the next update?

**Comment by waza-ari** [comment]
Hi @codebude,

thanks for your issue. The issue you mention is not happening within this project, it's happening within an upstream dependency `python-keycloak` (https://github.com/marcospereirampj/python-keycloak). 

Its this file that is causing the deprecation warning: https://github.com/marcospereirampj/python-keycloak/blob/5957607ad07536b94d878c3ce5d403c212b35220/src/keycloak/_version.py#L26

This issue should be filed against their repository, there's nothing we can do here.

It has been introduced in December 2022 btw :) https://github.com/marcospereirampj/python-keycloak/commit/fa955b759f6d7ce6e19ee833db0ce3cf961c114b

**Comment by codebude** [comment]
Hi @waza-ari ,

thanks for the fast feedback and sorry, that even my second issue a your repository was somehow invalid. I promise: The next issue will be related to your project in any case. ;-)

I opened a ticket over at python-keycloak: https://github.com/marcospereirampj/python-keycloak/issues/477

**Comment by waza-ari** [comment]
No worries, this project is not perfect by any means, so keep em coming! Thanks for the feedback.
