### ISSUE TITLE
Feature: Make JWT decode options configurable

### ISSUE THREAD

**Issue by codebude** [waza-ari/fastapi-keycloak-middleware#14]
This is not an issue, but a feature request.

**Why**
There might be constellations where the token providers don't pass the client_id as audience or where other things of the token differ.
Thus it would be helpful, to be able to configure the token decoding options.

**How?**
Make the jwt_decode options, currently hard-coded, configurable via the KeycloakConfiguraton of your library:
https://github.com/waza-ari/fastapi-keycloak-middleware/blob/main/fastapi_keycloak_middleware/keycloak_backend.py#L114

```python
 options = {
                "verify_signature": True,
                "verify_aud": True,
                "verify_exp": True,
            }
```

**Comment by waza-ari** [comment]
I like the idea of making this configurable. I'll hopefully find some time on the weekend to spend some time on this library again, I'll give it a shot and let you know.

**Comment by waza-ari** [comment]
Hi @codebude, I've added this feature and created a test release v0.3.0 on the Test PyPi instance: https://test.pypi.org/project/fastapi-keycloak-middleware/

Would you be willing to [use the test repository](https://stackoverflow.com/questions/73447611/how-do-i-install-packages-from-test-pypi-org-using-poetry) and use the v0.3.0 version?

**Comment by waza-ari** [comment]
Version 0.3.0 has just been released on production containing these changes.

**Comment by codebude** [comment]
Hi @waza-ari ,

sorry for the late reply. I was a couple of days in "offline world". I just tested the new version and it works flawlessly! Thanks for the fast implementation of my request.
