### ISSUE TITLE
Error AuthClaimMissing with client credentials as grant type

### ISSUE THREAD

**Issue by kaioenzo** [waza-ari/fastapi-keycloak-middleware#17]
Since I started making requests to my endpoint with a jwt created with client credential as grant type, I receive a 401 return error with the message "An error occurred: AuthClaimMissing". I've been working with the basic configuration of my Keycloak client, it's just a client with basic authorization. Looking in the code, I can't find the reason for this...

**Comment by waza-ari** [comment]
Hi @kaioenzo , thanks for using this library. It could be related to #14. To verify, could you post one example JWT that is causing the error? You can of course remove sensitive information 

My assumption right now is that your JWT will be missing the `aud` claim, which is currently being verified without options to change this configuration. That's what #14 is changing, there's already a test release `v0.3.0` on test Pypi.

**Comment by kaioenzo** [comment]
Yes, of course! Below is my jwt undecoded.
`{
  "exp": 1693603173,
  "iat": 1693567173,
  "jti": "39c77550-985a-409f-a29c-0f3f49df70e4",
  "aud": "account",
  "sub": "2d6baa03-7c5c-4d02-8f88-f2934fb32d0c",
  "typ": "Bearer",
  "azp": "example-client",
  "acr": "1",
  "allowed-origins": [
    "**",
    "*"
  ],
  "realm_access": {
    "roles": [
      "offline_access",
      "default-roles-example-realm",
      "uma_authorization"
    ]
  },
  "resource_access": {
    "example-client": {
      "roles": [
        "admin"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "email profile",
  "email_verified": true,
  "clientId": "example-client",
  "preferred_username": "service-account-example-client",
  "given_name": "",
  "family_name": "",
}`

Also, nice work with the library! It's really helpful.

**Comment by ducalai** [comment]
Same issue here with the message "An error occurred: AuthClaimMissing". I tried to turn on more detailled logging, but got not very more info 
`2023-09-04 13:19:05,129 [DEBUG] fastapi_keycloak_middleware.keycloak_backend: Using keycloak public key to validate token
2023-09-04 13:19:05,134 [ERROR] fastapi_keycloak_middleware.middleware: An error occurred while authenticating the user`
I think we are missing a piece to correctly configure the `aud` in the token. For me, it is always set to `account` (like in @kaioenzo's jwt example). 
Thanks for the library, it will help a lot!

**Comment by waza-ari** [comment]
Thanks for the additional information. I won't be able to look today, but will have a look tomorrow during the evening and let you know. Any details you could share regarding the Keycloak Realm or Client configuration that helps to reproduce the example would help.

**Comment by ducalai** [comment]
My clients configurations are really basic:
- client A (API): set client ID, client authentication to On (confidential) and set a password in Credentials tab
- client B (dashboard): set client ID, client authentication to Off (public), Valid redirect URIs to *, Web origins to * and Authenticate flow to Standard flow, Direct access grants and implicit flow
All other settings are default ones

I also define a user to test login.

Then, I tried Authorization_code flow with postman:
Get a code:
`curl --location 'http://localhost:8083/realms/myrealm/protocol/openid-connect/auth?client_id=dashboard&response_type=code&state=fj8o3n7bdylop4'`
Get a token
`curl --location 'http://localhost:8083/realms/myrealm/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'client_id=dashboard' \
--data-urlencode 'code=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' \
--data-urlencode 'scope=openid profile email'`

Finally use the token in Header when calling my protected API endpoint using Authorization: Token <token>

**Comment by ducalai** [comment]
I found it out. It has nothing to do with your lib.
As mentioned in your #9 closed issue, there are two fix possible. In Keycloak you can:

- use the audience resolve mechanism ([https://www.keycloak.org/docs/latest/server_admin/index.html#_audience_resolve](https://www.keycloak.org/docs/latest/server_admin/index.html#_audience_resolve)) if your service relies on roles in the token : create a client role, and assign it to users
- or, hardcode the audience using a protocol mapper ([https://www.keycloak.org/docs/latest/server_admin/#_audience_hardcoded](https://www.keycloak.org/docs/latest/server_admin/#_audience_hardcoded)) directly on the client by using the [client id]-dedicated client scope or by creating a client scope with a mapper and assigning it to the client

Sorry for the wrong issue...

**Comment by waza-ari** [comment]
Sorry for the late reply and thanks @ducalai for the information! @kaioenzo, does that apply to you as well?

**Comment by waza-ari** [comment]
No further comment, assuming the issue has been resolved.
