### ISSUE TITLE
OpenAPI support

### ISSUE THREAD

**Issue by ducalai** [waza-ari/fastapi-keycloak-middleware#24]
Once my FastAPI protected with the library, how can I improve OpenAPI docs with Authorize button and little locks next to each protected path operations?

Any help or suggestion will be appreciated...

**Comment by ducalai** [comment]
Simply using the `password` flow and adding FastAPI `OAuth2PasswordBearer` implementation as dependency in all protected desired path operations is enough?

Does it only affect OpenAPI docs page? I seems that I'm still able to call my API path operations with different clients and different flows, i.e `Client Credentials` or `Implicit` or `Authorization_code`.

Can you just confirm, please.

**Comment by heralight** [comment]
To add openidconnect to fastapi openapi ui, you can follow:
[https://www.hera.cc/2024/03/integrating-openidconnect-with-fastapis-openapi-ui/](https://www.hera.cc/2024/03/integrating-openidconnect-with-fastapis-openapi-ui/)

**Comment by waza-ari** [comment]
Hi guys,

version 0.4.0 (for now [available on test PyPi](https://test.pypi.org/project/fastapi-keycloak-middleware/)) does include a new feature that supports the Swagger UI including the Authorise button.

Please refer to:

- The [v0.4.0 release notes](https://github.com/waza-ari/fastapi-keycloak-middleware/releases/tag/v0.4.0) detailing the changes
- The [updated docs](https://fastapi-keycloak-middleware.readthedocs.io/en/latest/usage.html#swagger-ui-integration)

If you find some time, I'd be happy for any additional testers.
