### ISSUE TITLE
Question: How does one handle authentication of multi-tenant applications in a deterministic way?

### ISSUE THREAD

**Issue by bclements** [waza-ari/fastapi-keycloak-middleware#25]
Let's say for example you have a frontend application that is <realmname>.domainname.com that uses our  api called api.domainname.com.  This is a fastapi api running in a single codebase.

Right now, your library requires that the keycloak config be set with a realm at app startup. The problem is that we don't know the realm and the api needs to be deterministic in order to configure the keycloak config of your middle ware. 

Any ideas how we could do this with your library or in general?

**Comment by cay89** [comment]
My issue is the same; the realm should be obtained at runtime (from the request) to make it usable for a multi-tenant application scenario with different authentication modes.

**Comment by waza-ari** [comment]
Hi, currently I have no use case for multi tenancy, and even though I do understand the request, I will not be able to find time to implement it any time soon I'm afraid. I'm more than open for pull requests though.
