### ISSUE TITLE
Exclude routes from auth

### ISSUE THREAD

**Issue by clabnet** [waza-ari/fastapi-keycloak-middleware#28]
My server is provide of swagger documentation pages.
`http://localhost:5005/swagger`

I would exclude auth for swagger routes. 
I added the excluded_patterns as is but it seems not working.
```
keycloak_config = KeycloakConfiguration(
   ...
    exclude_patterns=["swagger"],
)
```

The error is `Your request is missing an 'Authorization' HTTP header`.
 
Any idea please ?

**Comment by waza-ari** [comment]
Hi,

assuming you're not mixing up routes (FastAPI usually doesn't expose the `/swagger` endpoint), you're probably just missing the leading slash. Also it's not passed to the KeycloakConfiguration but to the `add_middleware()` call.

```
excluded_routes = [
    "/docs",
    "/openapi.json",
    "/redoc"
]

app.add_middleware(
    ....
    exclude_patterns=excluded_routes,
)
```

Please see the documentation for further details: https://fastapi-keycloak-middleware.readthedocs.io/en/latest/advanced_topics.html#excluding-endpoints
