### ISSUE TITLE
JSONResponse instead of PlainTextResponse

### ISSUE THREAD

**Issue by cay89** [waza-ari/fastapi-keycloak-middleware#33]
It would be great if the middleware could be configurable to return JSONResponse instead of PlainTextResponse in case of an error. My frontend application expects JSON responses, and right now I have to apply some sort of workaround to handle this.

**Comment by waza-ari** [comment]
Hi @cay89,

please check if commit 5922577ec39d859b9fc48f4d0c5faf0ebc6819a7 could satisfy your requirements. It makes more sense to return JSON responses, totally agree.

**Comment by cay89** [comment]
I'm ok with that, thanks.

**Comment by waza-ari** [comment]
Okay, thanks for confirming. I'll cut a new release later containing this change.
