### ISSUE TITLE
API returns 401 Unauthorized on Options Preflight Calls

### ISSUE THREAD

**Issue by nabil-ak** [waza-ari/fastapi-keycloak-middleware#41]
The API is responding with an **401 Unauthorized** when making an OPTIONS call.

<img width="1076" alt="Screenshot 2024-04-25 at 12 30 05" src="https://github.com/waza-ari/fastapi-keycloak-middleware/assets/79709528/27054b8a-bb14-4867-bf42-4b25d4fc41b9">

I also configured the CORS Middleware like that:

`app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)`

Is this a bug with the package, or am I doing something wrong?

**Comment by waza-ari** [comment]
Hi Nabil,

that is certainly not intended. Could you please confirm the order I which you are adding the two middlewares?

In FastAPI, the middlewares are executed in inverse order, so the middleware you add first (in code) is executed last. Could you therefore confirm that you add this middleware before the `CORSMiddleware`?

If that is the issue I would amend the docs and add a hint for this scenario.

Thanks

**Comment by nabil-ak** [comment]
Hi Daniel,

thanks for the fast reply.
You're right, it's the order of the middleware that was causing the issue.


```
app = FastAPI()

app.add_middleware(
     KeycloakMiddleware,
     keycloak_configuration=keycloak_config,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
```


It worked with this order, thank you!

**Comment by frtozzo87** [comment]
Hi, I also added app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

but i still have the error Your request is missing an 'Authorization' HTTP header.

The import that i'm using is: from fastapi.middleware.cors import CORSMiddleware as CORSMiddleware

**Comment by nabil-ak** [comment]
@frtozzo87  Did you checked the order when you mount the middleware?
KeycloakMiddleware first then CORSMiddleware....

**Comment by frtozzo87** [comment]
Yes...this is my code:

app.add_middleware(
    KeycloakMiddleware,
    keycloak_configuration=keycloak_config,
)


app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)



@app.get("/")
async def root():
    return {"message": "Hello World"}


But in the browser i have Your request is missing an 'Authorization' HTTP header

**Comment by waza-ari** [comment]
@frtozzo87 Can you please give a screenshot of your attempt, including the request and response headers? What are you trying to access using which HTTP method?

**Comment by frtozzo87** [comment]
<img width="1064" alt="Schermata 2024-05-02 alle 10 18 26" src="https://github.com/waza-ari/fastapi-keycloak-middleware/assets/79852502/13c786d5-3e85-41be-b2d4-15dc77e40515">

**Comment by waza-ari** [comment]
Well... you're not sending any authentication token with your request. I'd argue the middleware is doing exactly what it's supposed to do, prohibiting unauthorised requests. Also, it's not about the preflight calls this issue is about.

I'd suggest not to continue the discussion in this issue, as it's unrelated. If you want you can open a separate one, but you need to include way more details including what you want to achieve, this is not clear to me.
