### ISSUE TITLE
No default value provided for swagger_client_id

### ISSUE THREAD

**Issue by pedjicaglavasica** [waza-ari/fastapi-keycloak-middleware#42]
### Issue
Documentation states that KeycloakConfiguration models _swagger_client_id_ field is optional and defaults to None. However when trying to instantiate KeycloakConfiguration without specifying a value for above mentioned field, Python raises an error as no default value is provided in schema definition
`swagger_client_id: Optional[str] = 
Field(
        title="Swagger Client ID",
 description="The client ID for the swagger UI."
    )`

### Solution
Change schema definition to 
`swagger_client_id: Optional[str] = 
Field(
default=None,
        title="Swagger Client ID",
 description="The client ID for the swagger UI."`

**Comment by waza-ari** [comment]
Thanks for the report, I noticed that myself yesterday as well, didn't have the time to fix it yet though. Will probably get around to it tomorrow.

**Comment by waza-ari** [comment]
Version v0.4.1 should fix this issue.
