### ISSUE TITLE
Authorization via Groups

### ISSUE THREAD

**Issue by martincollado** [waza-ari/fastapi-keycloak-middleware#44]
Hi, I'd like to know if would be possible to apply the authorization via groups memberships. We have several groups and members that we're using as a first layer of permissions. Do you have any clue if would be possible to achieve that with this middleware?

**Comment by waza-ari** [comment]
Hi @martincolladodev,

that is possible, yes. Ultimately, the library doesn't care how the claim within the AT is filled. Whether it contains a list of realm roles, client roles or groups doesn't matter too much, as long as it's a list of strings. You would need to define a mapper in Keycloak to map group memberships to a claim of your choice. You can then configure this middleware to use the claim as [described here](https://fastapi-keycloak-middleware.readthedocs.io/en/latest/authorization.html#claim-authorization).

There is a preconfigured mapper (type `Group Membership`) you can simply add to the custom scope of your client, for example like this:

<img width="1073" alt="image" src="https://github.com/waza-ari/fastapi-keycloak-middleware/assets/4508976/08c0d3f7-2524-4bbe-8742-08578180c4d9">

This will add a claim called `testgroups` to the access token:

<img width="1123" alt="image" src="https://github.com/waza-ari/fastapi-keycloak-middleware/assets/4508976/bf577c7c-d637-48b6-ae7d-58755be0a6b2">

This you can then use according to the docs, the same way as you'd use roles:

```python
setup_keycloak_middleware(
    app,
    keycloak_configuration=keycloak_config,
    get_user=auth_get_user,
    authorization_method=AuthorizationMethod.CLAIM,
    authorization_claim="testgroups"
)
```

Optionally, you can configure an `scope_mapper` method that maps the groups to whatever permissions you use within your application.

**Comment by waza-ari** [comment]
Closing this as there was no feedback and it likely has nothing to do with the library itself.

**Comment by martincollado** [comment]
Thank you very much for your response and explanation, sorry for the delay in the response, we already implemented the solution.
