### ISSUE TITLE
Exclude some endpoints

### ISSUE THREAD

**Issue by frtozzo87** [waza-ari/fastapi-keycloak-middleware#50]
I have the same endpoints in both get and post, I want to exclude GET calls from keycloak.

How i can do it? i have to use a prefix for GET function, or i can exclude it in others ways?

**Comment by waza-ari** [comment]
Hi, as of today this is a known limitation. See also the existing enhancement request in #3 . I'm yet to find a neat way of doing that, any ideas, proposals or even PRs are more than welcome. Closing this in favor of #3 .
