### ISSUE TITLE
TypeError: setup_keycloak_middleware() got an unexpected keyword argument 'authorization_method'

### ISSUE THREAD

**Issue by KingDracula** [waza-ari/fastapi-keycloak-middleware#54]
i was coding with docs but dont work ,how to config authorization thanks 
![image](https://github.com/waza-ari/fastapi-keycloak-middleware/assets/13584613/de901ee0-f98d-4984-85fa-04cf26e44074)

![image](https://github.com/waza-ari/fastapi-keycloak-middleware/assets/13584613/b5c55ff6-9a14-42ef-a3d9-e381eb57ef1e)

**Comment by waza-ari** [comment]
Hi, thanks for raising this issue! It does seem to be an error in the documentation, the authorization related args have to be added to the KeycloakConfiguration. Check the API references for details, I’ll try to work on the docs over the weekend if time permits.
