### ISSUE TITLE
how to config the authorization claim in keycloak

### ISSUE THREAD

**Issue by TOTom** [waza-ari/fastapi-keycloak-middleware#55]
hi , this middleware is great, it can resolve my problem when authentication. but when I want to use the authorization, I don't understand , how should I setup it in keycloak. for example, if I use the following configuration,   what should I do in keycloak?
```
authorization_method=AuthorizationMethod.CLAIM,
authorization_claim="scope"
````

**Comment by waza-ari** [comment]
Authorisation is role based (*), so basically you'll need to add a claim (usually called `roles` or `groups`) to your token. In Keycloak this is done via mappers, you can find an example screenshot in #34 .

*) Technically, it doesn't matter how that list of string is constructed. It can be a list of realm roles, a list of client roles, a list of groups or even a fixed list, as long as its a list of strings it can be used by the library.

**Comment by TOTom** [comment]
thanks , it works
