### ISSUE TITLE
authorization_claim support  nested structure

### ISSUE THREAD

**Issue by TOTom** [waza-ari/fastapi-keycloak-middleware#56]
hi, when authorization_claim  is a  "nested structure", it doesn't work. for example:
token_info:
{
  "realm_access: {
       'roles': ['default-roles-lng', 'offline_access', 'admin', 'uma_authorization', 'admin']
    }
}
if I set the  authorization_claim="realm_access.roles",  it cannot get the value.

**Comment by waza-ari** [comment]
Hi, please see #34 regarding this.
