### ISSUE TITLE
Having trouble getting docs to have keycloak as an authentication method

### ISSUE THREAD

**Issue by ghost** [waza-ari/fastapi-keycloak-middleware#69]
**Keycloak Authentication Not Working as Expected in Documentation**

I'm having trouble getting my documentation to use Keycloak as the authentication method. I'm not sure what I've configured incorrectly. The authorization in my documentation looks like this:

![image](https://github.com/user-attachments/assets/a49a9364-8c14-447a-8b6f-3513bb780e70)

**Endpoint Code:**

Here's the code for the endpoint that's supposed to be protected by Keycloak:

```python
import logging
from typing import Any

from fastapi import APIRouter, Depends, Request
from fastapi_keycloak_middleware import get_user

router = APIRouter()
logger = logging.getLogger(__name__)

@router.get("/protected-by-keycloak")
async def protected_route(
    request: Request,
    _user: dict[str, Any] = Depends(get_user),
) -> dict[str, Any]:
    # Log headers for debugging
    logger.info("Request headers: %s", dict(request.headers))

    return {
        "message": "You have access!",
        "headers": dict(request.headers),
    }
```

**Main.py (Middleware Setup):**

And here's the `main.py` file where I'm setting up the Keycloak middleware:

```python
from app.core.log_config import init_logging

init_logging()

import logging
from contextlib import asynccontextmanager

import sentry_sdk
from fastapi import FastAPI
from fastapi.routing import APIRoute
from fastapi_keycloak_middleware import KeycloakConfiguration, setup_keycloak_middleware
from starlette.middleware.cors import CORSMiddleware

from app.api.main import api_router
from app.core.config import settings
from app.utils import ensure_keycloak_realm_and_client

logging.getLogger("fastapi_keycloak_middleware").setLevel(logging.NOTSET)

logger = logging.getLogger(__name__)

def custom_generate_unique_id(route: APIRoute) -> str:
    return f"{route.tags[0]}-{route.name}"

if settings.SENTRY_DSN and settings.ENVIRONMENT != "local":
    sentry_sdk.init(dsn=str(settings.SENTRY_DSN), enable_tracing=True)

@asynccontextmanager
async def lifespan(_: FastAPI):
    # Startup
    ensure_keycloak_realm_and_client()
    print("Keycloak initialization complete.")
    yield
    # Shutdown
    pass

app = FastAPI(
    title=settings.PROJECT_NAME,
    openapi_url=f"{settings.API_V1_STR}/openapi.json",
    docs_url=f"{settings.API_V1_STR}/docs",
    redoc_url=f"{settings.API_V1_STR}/redoc",
    generate_unique_id_function=custom_generate_unique_id,
    lifespan=lifespan,
)

# Set all CORS enabled origins
if settings.BACKEND_CORS_ORIGINS:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[
            str(origin).strip("/") for origin in settings.BACKEND_CORS_ORIGINS
        ],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

# Add this before the Keycloak configuration
logger.info(
    "Initializing Keycloak with URL: %s, Realm: %s",
    settings.KEYCLOAK_URL,
    settings.KEYCLOAK_REALM,
)

# Set up Keycloak configuration
keycloak_config = KeycloakConfiguration(
    url=settings.KEYCLOAK_URL,
    realm=settings.KEYCLOAK_REALM,
    client_id=settings.KEYCLOAK_CLIENT_ID,
    reject_on_missing_claim=False,
    verify=True if settings.ENVIRONMENT != "local" else False,
    authentication_scheme="Bearer",
    swagger_client_id=settings.KEYCLOAK_CLIENT_ID,
    claims=["sub", "name", "email"],
)

print(keycloak_config)

# Add the Keycloak middleware with Swagger UI configuration
setup_keycloak_middleware(
    app,
    keycloak_configuration=keycloak_config,
    add_swagger_auth=True,  # Enable Swagger UI authentication
    swagger_auth_scopes=["openid", "profile"],  # Standard OpenID Connect scopes
    swagger_auth_pkce=True,  # Enable PKCE for better security
    exclude_patterns=[
        r"/api/v1/docs.*",  # Allow access to Swagger UI without authentication
        r"/api/v1/openapi.json",  # Allow access to OpenAPI schema
        r"/api/v1/redoc.*",  # Allow access to ReDoc
    ],
    swagger_openId_base_url=f"{settings.KEYCLOAK_URL}/realms/master/.well-known/openid-configuration",
    swagger_scheme_name="keycloak",
)

app.include_router(api_router, prefix=settings.API_V1_STR)
```

**Additional Information:**

*   I've ensured that the Keycloak realm and client are correctly set up.
*   I'm using the `fastapi-keycloak-middleware` library.

**Questions:**

1. Is there anything obviously wrong in my configuration that would prevent Keycloak authentication from working correctly in the documentation?
2. Are there any specific settings or configurations I should double-check within Keycloak itself?

Any help or guidance would be greatly appreciated!

**Comment by waza-ari** [comment]
Hey, could it be related to the same issue as described in #65?

Do you see anything in the browser console?

**Comment by ghost** [comment]
Thank you yes reviewing that issue helped but it was a bit unclear in the documentation when using Docker with internal and external networks.

**Setup:**

I'm using a Dockerized environment. My Keycloak configuration looks like this:

```python
keycloak_config = KeycloakConfiguration(
    url=settings.KEYCLOAK_URL, # Internal network URL
    realm=settings.KEYCLOAK_REALM,
    client_id=settings.KEYCLOAK_CLIENT_ID,
    reject_on_missing_claim=False,
    verify=True if settings.ENVIRONMENT != "local" else False,
    authentication_scheme="Bearer",
    swagger_client_id=settings.KEYCLOAK_CLIENT_ID,
    claims=["sub", "name", "email"],
)
```

**Question:**

In a Docker setup with both internal (container-to-container) and external (outside Docker) network access, should `KEYCLOAK_URL` point to the internal URL (e.g., `http://keycloak:8080`) or the external URL (e.g., `http://localhost:8082`)?

**My Experience:**

I found that the Swagger documentation only worked after I changed `swagger_openId_base_url` in `setup_keycloak_middleware` to use the external network URL:

```python
setup_keycloak_middleware(
    app,
    keycloak_configuration=keycloak_config,
    add_swagger_auth=True,
    swagger_auth_scopes=["openid", "profile"], 
    swagger_auth_pkce=True, 
    exclude_patterns=[
        r"/api/v1/docs.*", 
        r"/api/v1/openapi.json",  
        r"/api/v1/redoc.*", 
    ],
    swagger_openId_base_url="http://localhost:8082", # External URL was needed
    swagger_scheme_name="keycloak",
)
```

**Request for Clarification:**

Could you please elaborate on the recommended approach for setting `KEYCLOAK_URL` when using internal and external networks in Docker?

**Comment by waza-ari** [comment]
Basically consider this:

- The middleware itself runs within FastAPI, which in turn (I assume) runs in a docker container. For the sake of fetching config from the discovery endpoint and potentially verifying tokens, its fine to use the internal URL, as its container to container configuration.
- The Swagger UI is a client sided Javascript application which runs within the context of your browser. The browser doesn't run within the container, and therefore has no access to any internal networking.

Does this make things more clear? If you have a idea how to improve documentation in this regard, I'd really appreciate a PR!

**Comment by ghost** [comment]
Will review the docs and update them thank you

**Comment by waza-ari** [comment]
Great, thanks! Closing this one for now. If there's any potential for improvement, feel free to open a PR for it :)
