### ISSUE TITLE
Keycloak Event Listener

### ISSUE THREAD

**Issue by Legendnic** [waza-ari/fastapi-keycloak-middleware#7]
Hi, sorry for opening a new thread here. I am actually want to ask if this library has any means to listen to all KC events. This is because i would like to do an operation based on events, such as post-email-verification. It will huge help if this can listen to an event. You might ask why i need such things. it is because i want to store user identity to application database, so it is easy for me to track down all application's record based on that stored activities. thanks

**Comment by waza-ari** [comment]
Hi, sorry for the late response. The purpose of the software is to provide a middleware for authentication in Keycloak specifically, it runs on some client application. There's no support for plugging into Keycloaks event system, and at this stage I don't plan to look into that
