### ISSUE TITLE
An error occurred: AuthClaimMissing

### ISSUE THREAD

**Issue by mbuotidem** [waza-ari/fastapi-keycloak-middleware#9]
When using version 0.2.2, and the Basic example here : https://fastapi-keycloak-middleware.readthedocs.io/en/latest/usage.html#basic-example, I get the error `An error occurred: AuthClaimMissing`. 

If I turn the usage of the introspection endpoint on, I'm able to successfully authenticate. Is there something I'm missing? 

```
import uvicorn
from fastapi import FastAPI
from fastapi_keycloak_middleware import KeycloakConfiguration, KeycloakMiddleware

# Set up Keycloak
keycloak_config = KeycloakConfiguration(
     url="https://sso.your-keycloak.com/",
     realm="my-realm",
     client_id="client-id-here",
     claims=["sub", "name", "email"], # Modify claims
     client_secret="secrethere",
     reject_on_missing_claim=False, # Control behaviour when claims are missing,
    #  use_introspection_endpoint=True
 )

app = FastAPI()
 
 # Add middleware with basic config
app.add_middleware(
     KeycloakMiddleware,
     keycloak_configuration=keycloak_config,
 )

@app.get("/")
async def root():
    return {"message": "Hello World"}




if __name__ == '__main__':
    uvicorn.run('app:app', host="127.0.0.1", port=8081)

```

**Comment by waza-ari** [comment]
Hi,

the `AuthClaimMissing` error is raised when one of the claims cannot be extracted.

In your example, `sub` is part of the `openid` scope, `name` is part of the `profile` scope and `email` has a dedicated scope called `email`. Depending on the setting of `use_introspection_endpoint`, two different methods are used to verify the token.

If `use_introspection_endpoint` is set to `false` (default behaviour), then only the scopes and claims sent as part of the access token can be extracted, as the signature is verified locally and no further request is made towards Keycloak. Whenever you request an access token (I assume you use some frontend), you can define the scopes that should be included. Make sure that you request at least the scopes `openid`, `profile` and `email` if you want to use claims that are part of these scopes. Alternatively, you can configure keycloak to always add these scopes to the token by setting them to `default` in the Keycloak client configuration.

![image](https://github.com/waza-ari/fastapi-keycloak-middleware/assets/4508976/0c8484b0-99c0-4830-a6ed-a7eb6efe9f11)

You can also check the claims that will be available in the token in the "Evaluate" tab of the same page in Keycloak, just make sure you select the same scopes there that you also request when obtaining the access token in the first place.

If `use_introspection_endpoint` is set to true, the library performs a request to the `userinfo` endpoint, and the answer to this request is used to extract the claims you specify. In your case, this reply does contain the claims you have configured, therefore you don't see any error message.

You can also turn on [more detailled logging](https://fastapi-keycloak-middleware.readthedocs.io/en/latest/advanced_topics.html#logging), you'll get more detailled messages indicating which claim is missing exactly.

**Comment by mbuotidem** [comment]
Thanks, for the detailed reply.  I'm actually grabbing the token directly using curl:
```
curl -d "client_id=client-id-here" -d "username=username-here" -d 'password=password-here' -d "grant_type=password" -d 'client_secret=client-secret-here' -d 'scopes=openid profile email' https://sso.your-keycloak.com/realms/my-realm/protocol/openid-connect/token
```
And here's a screenshot of the jwt - which matches up to what I get when I use the "Evaluate" tab: 
![image](https://github.com/waza-ari/fastapi-keycloak-middleware/assets/4692052/a72c2574-8ba1-4159-8b7a-8368a0b8d721)


I also turned on logging at `DEBUG` but unfortunately it doesn't tell me which claims are missing, just this:

```
INFO:     127.0.0.1:64675 - "GET / HTTP/1.1" 401 Unauthorized
2023-07-26 10:15:09,025 - fastapi_keycloak_middleware.middleware - DEBUG - Keycloak Middleware is handling request
2023-07-26 10:15:09,025 - fastapi_keycloak_middleware.middleware - INFO - Trying to authenticate user
2023-07-26 10:15:09,025 - urllib3.util.retry - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-07-26 10:15:09,025 - urllib3.util.retry - DEBUG - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)
2023-07-26 10:15:09,025 - fastapi_keycloak_middleware.keycloak_backend - DEBUG - Using keycloak public key to validate token
2023-07-26 10:15:09,026 - fastapi_keycloak_middleware.middleware - ERROR - An error occurred while authenticating the user
INFO:     127.0.0.1:64675 - "GET /favicon.ico HTTP/1.1" 401 Unauthorized

```

**Comment by mbuotidem** [comment]
After spending some quality time with the Keycloak docs, I figured out the issue. My understanding of OAuth is still fledgling so please feel free to correct any inaccuracies here. It appears that python-keycloak which this library uses requires the client_id to be part of the token `aud` claim: https://github.com/marcospereirampj/python-keycloak/blob/5957607ad07536b94d878c3ce5d403c212b35220/src/keycloak/keycloak_openid.py#L537. 

One fix is to create a client role, and assign said role to the user. The audience resolve mechanism described at https://www.keycloak.org/docs/latest/server_admin/index.html#_audience_resolve would automagically add that the client_id of the authorized party to the `aud` claim. 

Another is to use https://www.keycloak.org/docs/latest/server_admin/#_audience_hardcoded to add the client_id to the token.
